### ISSUE TITLE
POPC Python Bindings for C++ Implementation

### ISSUE THREAD

**Issue by rlichtenwalter** [pepe78/POPC-examples-python#1]
Hi Peter,

I've written an efficient C++ implementation that reduces the time to compute, obviously depending on data set, but by a factor of 100s for large data sets on which I am working. This brings the POPC method into reach for a much broader range of data sets. I have also written some Python bindings, not quite finished and aren't yet in the repository, because I'm working on them elsewhere.

https://github.com/rlichtenwalter/popc

I have some questions for some enhanced functionality I'd like to support:
1. First, I'm using mlpack for kmeans. It offers several algorithm templates, but I've found the naive algorithm to actually be the fastest in the general case, perhaps due to greater optimization. Nonetheless, in large data sets, clustering with k=n/2 clusters is prohibitive. Is clustering really necessary? It seems that little would be lost from just randomly assigning instances into pairs and beginning POPC from there. Do you have any intuition to share about this?
2. It would be ideal to support not only clustering in a cluster fit method, but also cluster assignment for new instances. My idea for doing this is to consider existing POPC cluster assignments fixed and to run the POPC iterations only allowing reassignment of new instances. Does seem like a sane approach? Do you perhaps have a better idea?

Best,

Ryan

**Comment by pepe78** [comment]
Hi Ryan,

that's cool someone did speedy C++ implementation! :)

1. you can make k-mean clustering / random assignments at the beginning optional - random should work as well, but would need to be verified - you can take examples as POPC to see if that works. [it could also be closest couples together instead of random? that should definitely work]
2. I am not really sure this would work great as whole purpose is to end up with optimal number of clusters as well. More research would be required for additional functionalities. [by only adding new assignments and not reshuffling you would end up with same amount of clusters, but this could be non optimal]

Cheers,
Peter

**Comment by rlichtenwalter** [comment]
Hi Peter,

Thank you for the rapid response. A quick follow-up, trying to be conscientious of your time.

1. Yeah, I was thinking that a fast alternative to random that would be safe for sure would be greedy (non-globally optimal) nearest neighbor pairing. Maybe I'll implement that sometime in the future and drop the k-means requirement. It's really slow for the size of data sets to which I'm now effectively applying POPC.
2. In our use case, we're using cluster output to generate features from a sparsely positive high-dimensional binary space into a much lower dimensional low-branching categorical (cluster assignment) space. Although separate clustering of validation and test sets may not lead to a globally optimal solution, re-clustering the entire data set incorporating testing data would constitute information leakage, as cluster assignments on training instances would leak information about test instances to subsequent classification steps. Given this use case, do you have any thoughts about doing post hoc transformations based on POPC clusters? One idea is certainly running the POPC procedure given fixed instances from training and movable instances from holdouts, and that was my original idea. A simpler idea would be to assign based on minimum cluster centroid distance, but while this is fine in the spirit of k-means, I think it's very much not in the spirit of POPC, since it won't necessarily align with the feature clustering. Does this make sense? Any thoughts?

Thanks for any time you can spare, and thanks for this algorithm, paper, and reference implementation. Very cool!

Ryan

**Comment by pepe78** [comment]
Hi Ryan,

1. cool :)
2. I am trying to understand why you would not want to run popc on dataset - so if you do have really really large amount of data (and popc would take literally forever), then I guess subsampling + popc + assigning of remaining data to created clusters only could work and probably returns the same clusters as popc on whole dataset would. but this would need to be verified again :). idea does sound cool and is worth experimenting with.

Hope this helps :)
Peter
